#!/usr/bin/env bash
# Script that shows info about subdomains

print_msg () {
    echo "The subdomain $1 is a $2 record and points to $3"
}

show_subd_info () {
    SUBS="www lb-01 web-01 web-02"
    if [ $# -eq 2 ]
        then
          URL=$2.$1
          IP="$(dig "$URL" +short)"
          REC="$(dig $URL | grep '^'"$URL" | cut -f4)"
          print_msg "$2" "$REC" "$IP"
    elif [ $# -eq 1 ]
        then
          for sub in $SUBS;do
            URL=$sub.$1
            IP="$(dig "$URL" +short)"
            REC="$(dig "$URL" | grep '^'"$URL" | cut -f4)"
            print_msg "$sub" "$REC" "$IP"
          done
    fi
}
show_subd_info $1 $2
