#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chmod -R 777 /etc/nginx
sed -i "/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n" /etc/nginx/sites-available/default
sudo service nginx restart

