#!/usr/bin/env bash
#  Bash script that displays the content of the file /etc/passwd.
# Your script should only display:
# username
# user id
# Home directory path for the user
FILE="/etc/passwd"
while IFS=: read -r line line2 line3 line4 line5 line6 line7
do
	echo "$line:$line3:$line6"
done < "$FILE"	
