#!/usr/bin/env bash
#  Bash script that displays the content of the file /etc/passwd.
# Your script should only display:
# username
# user id
# Home directory path for the user
LINES=$(cut -d ":" -f 1,3,6 /etc/passwd)
while "$LINES"
do
	echo "$LINES"
done
