#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
s=1
h=0
while [ $h -lt 13 ]
do
echo "Hour: $h"
	while [ $s -lt 60 ]
	do
		echo "$s"
		s=$((s+1))
	done
s=1
h=$((h+1))
done
